abimees:
  jwt:
    issuer-name: ${JWT_ISSUER:abimees}
    secret: ${JWT_SECRET:Z1ON0101}

server:
  port: 8090

spring:
  security:
    filter:
      order: 10
    user:
      password: Test12345_
  flyway:
    clean-on-validation-error: false
    locations:
      - classpath:db/vendorspecific/{vendor}
      - classpath:db/migration
    datasource:
      url: ${DB_URL:jdbc:h2:mem:test}
      username: ${DB_USERNAME:sa}
      password: ${DB_PASSWORD:}
      hikari:
        maximum-pool-size: 50
        idle-timeout: 180000
      h2:
        console:
          enabled: true
      jpa:
        show-sql: ${SHOWSQL:true}
        hibernate:
          ddl-auto: validate
        open-in-view: true
        properties:
          hibernate:
            format_sql: ${SHOWSQL:true}
            dialect: ${DB_DIALECT:org.thievent.abimees.utils.hibernate.H2DialectExtended}
